**Домашнее задание 2**

Во втором дз предлагается поработать с достаточно большим датасетом, [описание](https://archive.ics.uci.edu/ml/datasets/bank+marketing). Решите предложенные задания с использованием модуля Pandas (NumPy, разумеется, тоже разрешен).

Использование условий и циклов крайне нежелательно (списковые включения это тоже цикл!), за это будут снижаться баллы.
Все задания равноценны (кроме нулевой).
В каждой задаче постарайтесь придумать несколько решений. Решением должен быть Jupyter notebook / ссылка на Colab

In [1]:
import pandas as pd
import numpy as np

In [2]:
url = 'https://raw.githubusercontent.com/Sketchjar/MachineLearningHD/main/bank_marketing_dataset.csv'

df = pd.read_csv(url)

In [4]:
df.head()

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,outcome
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,57,services,married,high.school,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,37,services,married,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,40,admin.,married,basic.6y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,56,services,married,high.school,no,no,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no

0. Каков размер датасета? Выведите первые 2 строки. Выведите две случайные строки. Какие типы колонок в датафрейме?

In [5]:
df.shape

(41188, 21)

In [6]:
df.head(2)

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,outcome
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,57,services,married,high.school,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no

In [7]:
df.sample(2)

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,outcome
32818,36,admin.,married,high.school,no,no,no,cellular,may,mon,...,1,999,0,nonexistent,-1.8,92.893,-46.2,1.299,5099.1,no
16196,36,admin.,single,high.school,no,no,no,cellular,jul,tue,...,3,999,0,nonexistent,1.4,93.918,-42.7,4.961,5228.1,no

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41188 entries, 0 to 41187
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             41188 non-null  int64
 1   job             41188 non-null  object
 2   marital         41188 non-null  object
 3   education       41188 non-null  object
 4   default         41188 non-null  object
 5   housing         41188 non-null  object
 6   loan            41188 non-null  object
 7   contact         41188 non-null  object
 8   month           41188 non-null  object
 9   day_of_week     41188 non-null  object
 10  duration        41188 non-null  int64
 11  campaign        41188 non-null  int64
 12  pdays           41188 non-null  int64
 13  previous        41188 non-null  int64
 14  poutcome        41188 non-null  object
 15  emp.var.rate    41188 non-null  float64
 16  cons.price.idx  41188 non-null  float64
 17  cons.conf.idx   41188 non-null  float64
 18  euribor3m       41188 non-null  float64
 19  nr.employed     41188 non-null  float64
 20  outcome         41188 non-null  object
dtypes: float64(5), int64(5), object(11)
memory usage: 6.6+ MB

1. Выведите основные статистические показатели для числовых признаков – количество значений, среднее, стандартное отклонение, min/max, медиану, верхнюю и нижнюю квартиль.

In [9]:
df.describe()

,age,duration,campaign,pdays,previous,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed
count,41188.00000,41188.000000,41188.000000,41188.000000,41188.000000,41188.000000,41188.000000,41188.000000,41188.000000,41188.000000
mean,40.02406,258.285010,2.567593,962.475454,0.172963,0.081886,93.575664,-40.502600,3.621291,5167.035911
std,10.42125,259.279249,2.770014,186.910907,0.494901,1.570960,0.578840,4.628198,1.734447,72.251528
min,17.00000,0.000000,1.000000,0.000000,0.000000,-3.400000,92.201000,-50.800000,0.634000,4963.600000
25%,32.00000,102.000000,1.000000,999.000000,0.000000,-1.800000,93.075000,-42.700000,1.344000,5099.100000
50%,38.00000,180.000000,2.000000,999.000000,0.000000,1.100000,93.749000,-41.800000,4.857000,5191.000000
75%,47.00000,319.000000,3.000000,999.000000,0.000000,1.400000,93.994000,-36.400000,4.961000,5228.100000
max,98.00000,4918.000000,56.000000,999.000000,7.000000,1.400000,94.767000,-26.900000,5.045000,5228.100000

2. Выведите число значений, уникальных значений, самое частое из значений (и его частоту) для всех остальных признаков.

In [10]:
df.describe(include=[object])

,job,marital,education,default,housing,loan,contact,month,day_of_week,poutcome,outcome
count,41188,41188,41188,41188,41188,41188,41188,41188,41188,41188,41188
unique,12,4,8,3,3,3,2,10,5,3,2
top,admin.,married,university.degree,no,yes,no,cellular,may,thu,nonexistent,no
freq,10422,24928,12168,32588,21576,33950,26144,13769,8623,35563,36548

3. Сколько в выборке неграмотных людей? А безработных? Какой процент в выборке разведенных людей?

In [11]:
len(df[df['education'] == 'illiterate']["education"]), df[df['education'] == 'illiterate'].shape[0] # два способа

(18, 18)

In [12]:
len(df[df["job"] == "unemployed"]["job"]), df[df['job'] == 'unemployed'].shape[0]

(1014, 1014)

In [13]:
df[df["marital"]=="divorced"].shape[0] / df.shape[0] * 100

11.197436146450421

4. Вставьте вместо пропусков в колонку job самое частое значение в этой колонке

In [14]:
set(df["job"])

{'admin.',
 'blue-collar',
 'entrepreneur',
 'housemaid',
 'management',
 'retired',
 'self-employed',
 'services',
 'student',
 'technician',
 'unemployed',
 'unknown'}

In [15]:
df["job"].value_counts()

admin.           10422
blue-collar       9254
technician        6743
services          3969
management        2924
retired           1720
entrepreneur      1456
self-employed     1421
housemaid         1060
unemployed        1014
student            875
unknown            330
Name: job, dtype: int64

In [16]:
df["job"].replace("unknown", "admin.", inplace=True)

In [17]:
df["job"].value_counts()

admin.           10752
blue-collar       9254
technician        6743
services          3969
management        2924
retired           1720
entrepreneur      1456
self-employed     1421
housemaid         1060
unemployed        1014
student            875
Name: job, dtype: int64

In [18]:
df["job"].mode()[0]

'admin.'

In [19]:
df["job"].replace("unknown", df["job"].mode()[0], inplace=True)

5. Сравните средний возраст женатых и одиноких людей

In [20]:
df[df["marital"]=="married"]["age"].mean()

42.30716463414634

In [21]:
df[df["marital"]=="single"]["age"].mean()

33.15871369294606

In [22]:
df[df["marital"]=="married"]["age"].mean() > df[df["marital"]=="single"]["age"].mean()

True

6. Добавьте в датафрейм признак "логарифм длины последнего звонка". Для некоторых моделей машинного обучения могут быть полезны подобные признаки.

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41188 entries, 0 to 41187
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             41188 non-null  int64
 1   job             41188 non-null  object
 2   marital         41188 non-null  object
 3   education       41188 non-null  object
 4   default         41188 non-null  object
 5   housing         41188 non-null  object
 6   loan            41188 non-null  object
 7   contact         41188 non-null  object
 8   month           41188 non-null  object
 9   day_of_week     41188 non-null  object
 10  duration        41188 non-null  int64
 11  campaign        41188 non-null  int64
 12  pdays           41188 non-null  int64
 13  previous        41188 non-null  int64
 14  poutcome        41188 non-null  object
 15  emp.var.rate    41188 non-null  float64
 16  cons.price.idx  41188 non-null  float64
 17  cons.conf.idx   41188 non-null  float64
 18  euribor3m       41188 non-null  float64
 19  nr.employed     41188 non-null  float64
 20  outcome         41188 non-null  object
dtypes: float64(5), int64(5), object(11)
memory usage: 6.6+ MB

In [25]:
df["log_last_call"] = np.log(df["duration"])
df.head()

/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:402: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,outcome,log_last_call
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,...,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no,5.564520
1,57,services,married,high.school,unknown,no,no,telephone,may,mon,...,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no,5.003946
2,37,services,married,high.school,no,yes,no,telephone,may,mon,...,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no,5.420535
3,40,admin.,married,basic.6y,no,no,no,telephone,may,mon,...,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no,5.017280
4,56,services,married,high.school,no,no,yes,telephone,may,mon,...,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no,5.726848

7. Выведите часть датасета, в которой будут все люди с минимальным в выборке возрастом, согласившиеся на срочный вклад

In [26]:
df["age"].min()

17

In [27]:
df[(df["age"]==df["age"].min())]

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,outcome,log_last_call
37140,17,student,single,unknown,no,yes,no,cellular,aug,wed,...,4,2,success,-2.9,92.201,-31.4,0.884,5076.2,no,6.068426
37539,17,student,single,basic.9y,no,yes,no,cellular,aug,fri,...,999,2,failure,-2.9,92.201,-31.4,0.869,5076.2,no,5.204007
37558,17,student,single,basic.9y,no,yes,no,cellular,aug,fri,...,4,2,success,-2.9,92.201,-31.4,0.869,5076.2,no,4.521789
37579,17,student,single,basic.9y,no,unknown,unknown,cellular,aug,fri,...,999,1,failure,-2.9,92.201,-31.4,0.869,5076.2,yes,6.210600
38274,17,student,single,unknown,no,no,yes,cellular,oct,tue,...,2,2,success,-3.4,92.431,-26.9,0.742,5017.5,yes,6.797940

In [25]:
df[(df["age"]==df["age"].min()) & (df["outcome"]=="yes")]

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,outcome,log_last_call
37579,17,student,single,basic.9y,no,unknown,unknown,cellular,aug,fri,...,999,1,failure,-2.9,92.201,-31.4,0.869,5076.2,yes,6.21060
38274,17,student,single,unknown,no,no,yes,cellular,oct,tue,...,2,2,success,-3.4,92.431,-26.9,0.742,5017.5,yes,6.79794

8. Создайте новый датафрейм, в который войдут 10 самых возрастных клиентов, которые работают. В нем строки должны быть отсортированы по возрасту в порядке убывания, а индексом должны являться числа от 0 до 9 включительно. Оставьте в новом датафрейме (помимо индекса) только колонки age, marital education, housing, loan

In [34]:
new_df = df.copy()
new_df = new_df[new_df["job"]!="unknown"]
new_df = new_df.sort_values(by="age", ascending=False).head(10)
new_df = new_df[['age', 'marital', 'education', 'housing', 'loan']]
new_df = new_df.reset_index()
new_df = new_df.drop(["index"], axis=1)
new_df

   age   marital          education housing loan
0   98   married           basic.4y     yes   no
1   98   married           basic.4y     yes   no
2   95  divorced           basic.6y      no   no
3   94   married           basic.9y      no   no
4   92   married            unknown     yes   no
5   92   married            unknown      no  yes
6   92  divorced            unknown      no   no
7   92   married            unknown      no  yes
8   91   married  university.degree      no  yes
9   91   married  university.degree     yes  yes

9. Создайте столбец с датой контакта. Дата должна соответствовать информации из столбцов month и day_of_week и относиться к 2021 году (в этом задании может быть, разумеется, много верных ответов, выведите любой)

In [51]:
df["month"]

0        may
1        may
2        may
3        may
4        may
        ...
41183    nov
41184    nov
41185    nov
41186    nov
41187    nov
Name: month, Length: 41188, dtype: object

In [52]:
df["day_of_week"]

0        mon
1        mon
2        mon
3        mon
4        mon
        ...
41183    fri
41184    fri
41185    fri
41186    fri
41187    fri
Name: day_of_week, Length: 41188, dtype: object

In [35]:
df["date_of_contact"] = df["day_of_week"] + "-" + df["month"] + "-" + "2021"
df

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,outcome,log_last_call,date_of_contact
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,...,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no,5.564520,mon-may-2021
1,57,services,married,high.school,unknown,no,no,telephone,may,mon,...,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no,5.003946,mon-may-2021
2,37,services,married,high.school,no,yes,no,telephone,may,mon,...,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no,5.420535,mon-may-2021
3,40,admin.,married,basic.6y,no,no,no,telephone,may,mon,...,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no,5.017280,mon-may-2021
4,56,services,married,high.school,no,no,yes,telephone,may,mon,...,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no,5.726848,mon-may-2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41183,73,retired,married,professional.course,no,yes,no,cellular,nov,fri,...,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,yes,5.811141,fri-nov-2021
41184,46,blue-collar,married,professional.course,no,no,no,cellular,nov,fri,...,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,no,5.948035,fri-nov-2021
41185,56,retired,married,university.degree,no,yes,no,cellular,nov,fri,...,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,no,5.241747,fri-nov-2021
41186,44,technician,married,professional.course,no,no,no,cellular,nov,fri,...,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,yes,6.091310,fri-nov-2021
41187,74,retired,married,professional.course,no,yes,no,cellular,nov,fri,...,1,failure,-1.1,94.767,-50.8,1.028,4963.6,no,5.476464,fri-nov-2021

In [40]:
set(df["month"])

{'apr', 'aug', 'dec', 'jul', 'jun', 'mar', 'may', 'nov', 'oct', 'sep'}

In [42]:
df["number_month"] = df["month"]
df["number_month"].replace("jun", 1, inplace=True)
df["number_month"].replace("mar", 3, inplace=True)
df["number_month"].replace("apr", 4, inplace=True)
df["number_month"].replace("may", 5, inplace=True)
df["number_month"].replace("jun", 6, inplace=True)
df["number_month"].replace("jul", 7, inplace=True)
df["number_month"].replace("aug", 8, inplace=True)
df["number_month"].replace("sep", 9, inplace=True)
df["number_month"].replace("oct", 10, inplace=True)
df["number_month"].replace("nov", 11, inplace=True)
df["number_month"].replace("dec", 12, inplace=True)

In [43]:
df

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,outcome,log_last_call,date_of_contact,number_month
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,...,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no,5.564520,mon-may-2021,5
1,57,services,married,high.school,unknown,no,no,telephone,may,mon,...,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no,5.003946,mon-may-2021,5
2,37,services,married,high.school,no,yes,no,telephone,may,mon,...,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no,5.420535,mon-may-2021,5
3,40,admin.,married,basic.6y,no,no,no,telephone,may,mon,...,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no,5.017280,mon-may-2021,5
4,56,services,married,high.school,no,no,yes,telephone,may,mon,...,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no,5.726848,mon-may-2021,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41183,73,retired,married,professional.course,no,yes,no,cellular,nov,fri,...,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,yes,5.811141,fri-nov-2021,11
41184,46,blue-collar,married,professional.course,no,no,no,cellular,nov,fri,...,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,no,5.948035,fri-nov-2021,11
41185,56,retired,married,university.degree,no,yes,no,cellular,nov,fri,...,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,no,5.241747,fri-nov-2021,11
41186,44,technician,married,professional.course,no,no,no,cellular,nov,fri,...,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,yes,6.091310,fri-nov-2021,11
41187,74,retired,married,professional.course,no,yes,no,cellular,nov,fri,...,failure,-1.1,94.767,-50.8,1.028,4963.6,no,5.476464,fri-nov-2021,11

In [47]:
df["date_of_contact_2"] = df["day_of_week"] + "-" + df["number_month"].astype(str) + "-" + "2021"
df

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,outcome,log_last_call,date_of_contact,number_month,date_of_contact_2
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,...,1.1,93.994,-36.4,4.857,5191.0,no,5.564520,mon-may-2021,5,mon-5-2021
1,57,services,married,high.school,unknown,no,no,telephone,may,mon,...,1.1,93.994,-36.4,4.857,5191.0,no,5.003946,mon-may-2021,5,mon-5-2021
2,37,services,married,high.school,no,yes,no,telephone,may,mon,...,1.1,93.994,-36.4,4.857,5191.0,no,5.420535,mon-may-2021,5,mon-5-2021
3,40,admin.,married,basic.6y,no,no,no,telephone,may,mon,...,1.1,93.994,-36.4,4.857,5191.0,no,5.017280,mon-may-2021,5,mon-5-2021
4,56,services,married,high.school,no,no,yes,telephone,may,mon,...,1.1,93.994,-36.4,4.857,5191.0,no,5.726848,mon-may-2021,5,mon-5-2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41183,73,retired,married,professional.course,no,yes,no,cellular,nov,fri,...,-1.1,94.767,-50.8,1.028,4963.6,yes,5.811141,fri-nov-2021,11,fri-11-2021
41184,46,blue-collar,married,professional.course,no,no,no,cellular,nov,fri,...,-1.1,94.767,-50.8,1.028,4963.6,no,5.948035,fri-nov-2021,11,fri-11-2021
41185,56,retired,married,university.degree,no,yes,no,cellular,nov,fri,...,-1.1,94.767,-50.8,1.028,4963.6,no,5.241747,fri-nov-2021,11,fri-11-2021
41186,44,technician,married,professional.course,no,no,no,cellular,nov,fri,...,-1.1,94.767,-50.8,1.028,4963.6,yes,6.091310,fri-nov-2021,11,fri-11-2021
41187,74,retired,married,professional.course,no,yes,no,cellular,nov,fri,...,-1.1,94.767,-50.8,1.028,4963.6,no,5.476464,fri-nov-2021,11,fri-11-2021

10. Какие два столбца исходного датафрейма наиболее скоррелированные?

In [31]:
df_corr = df.corr()
df_corr

<ipython-input-31-0c96883f2151>:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  df_corr = df.corr()

,age,duration,campaign,pdays,previous,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,log_last_call
age,1.000000,-0.000866,0.004594,-0.034369,0.024365,-0.000371,0.000857,0.129372,0.010767,-0.017725,0.008995
duration,-0.000866,1.000000,-0.071699,-0.047577,0.020640,-0.027968,0.005312,-0.008173,-0.032897,-0.044703,0.810967
campaign,0.004594,-0.071699,1.000000,0.052584,-0.079141,0.150754,0.127836,-0.013733,0.135133,0.144095,-0.194820
pdays,-0.034369,-0.047577,0.052584,1.000000,-0.587514,0.271004,0.078889,-0.091342,0.296899,0.372605,-0.076292
previous,0.024365,0.020640,-0.079141,-0.587514,1.000000,-0.420489,-0.203130,-0.050936,-0.454494,-0.501333,0.048519
emp.var.rate,-0.000371,-0.027968,0.150754,0.271004,-0.420489,1.000000,0.775334,0.196041,0.972245,0.906970,-0.043706
cons.price.idx,0.000857,0.005312,0.127836,0.078889,-0.203130,0.775334,1.000000,0.058986,0.688230,0.522034,-0.009893
cons.conf.idx,0.129372,-0.008173,-0.013733,-0.091342,-0.050936,0.196041,0.058986,1.000000,0.277686,0.100513,0.027636
euribor3m,0.010767,-0.032897,0.135133,0.296899,-0.454494,0.972245,0.688230,0.277686,1.000000,0.945154,-0.044825
nr.employed,-0.017725,-0.044703,0.144095,0.372605,-0.501333,0.906970,0.522034,0.100513,0.945154,1.000000,-0.065710
log_last_call,0.008995,0.810967,-0.194820,-0.076292,0.048519,-0.043706,-0.009893,0.027636,-0.044825,-0.065710,1.000000

In [50]:
df_corr_sorted = df_corr.unstack().sort_values(ascending=False)
df_corr_sorted

age            age              1.000000
duration       duration         1.000000
nr.employed    nr.employed      1.000000
euribor3m      euribor3m        1.000000
cons.conf.idx  cons.conf.idx    1.000000
                                  ...
euribor3m      previous        -0.454494
nr.employed    previous        -0.501333
previous       nr.employed     -0.501333
pdays          previous        -0.587514
previous       pdays           -0.587514
Length: 121, dtype: float64

In [47]:
df_corr_sorted[df_corr_sorted<1]

euribor3m     emp.var.rate    0.972245
emp.var.rate  euribor3m       0.972245
euribor3m     nr.employed     0.945154
nr.employed   euribor3m       0.945154
              emp.var.rate    0.906970
                                ...
euribor3m     previous       -0.454494
nr.employed   previous       -0.501333
previous      nr.employed    -0.501333
pdays         previous       -0.587514
previous      pdays          -0.587514
Length: 110, dtype: float64

In [49]:
df_corr_sorted[df_corr_sorted<1].index[0]

('euribor3m', 'emp.var.rate')